import { Mail, Calendar, HardDrive } from "lucide-react";

export default function GoogleIntegrations() {
    const integrations = [
        {
            icon: <Mail className="w-8 h-8 text-[#FF3B30]" />,
            title: "Gmail",
            description: "Read and send emails through AI-assisted commands"
        },
        {
            icon: <Calendar className="w-8 h-8 text-[#FF6B47]" />,
            title: "Google Calendar",
            description: "Create and manage calendar events automatically"
        },
        {
            icon: <HardDrive className="w-8 h-8 text-[#FF9E5E]" />,
            title: "Google Drive",
            description: "Store and organize documents generated by the AI assistant"
        }
    ];

    return (
        <section className="py-24 px-4 bg-[#0F1012] relative z-10 border-t border-white/5">
            <div className="max-w-7xl mx-auto">
                <div className="text-center mb-16">
                    <h2 className="text-3xl md:text-5xl font-display font-bold text-white mb-6">Google Integrations</h2>
                    <p className="text-xl text-gray-400 max-w-2xl mx-auto font-light leading-relaxed">
                        These integrations allow Varticas to automate productivity workflows using Google services.
                    </p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {integrations.map((item, index) => (
                        <div key={index} className="p-8 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors">
                            <div className="w-16 h-16 rounded-xl bg-[#07080A] border border-white/10 flex items-center justify-center mb-6">
                                {item.icon}
                            </div>
                            <h3 className="text-2xl font-bold text-white mb-4">{item.title}</h3>
                            <p className="text-gray-400 font-light leading-relaxed">{item.description}</p>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
}
